### ISSUE TITLE
在window上不能正常运行

### ISSUE THREAD

**Issue by helailiang** [muxueqz/bsn-proxy#1]

**Comment by helailiang** [comment]
![image](https://user-images.githubusercontent.com/46402797/90620316-dd7f9180-e244-11ea-84b4-e49c671cc9b2.png)

**Comment by muxueqz** [comment]
> ![image](https://user-images.githubusercontent.com/46402797/90620316-dd7f9180-e244-11ea-84b4-e49c671cc9b2.png)

请问你运行的参数是什么呢？看起来是你传的bsn-url格式有问题，你可以把bsn-url贴一部分，要包含https://的那里

**Comment by muxueqz** [comment]
我试了一下，可以重现这个问题，
在Windows下参数不能加引号，所以用法是这样的：
```bash
python3 bsn-proxy.py --bsn-url https://hk.bsngate.com/api/[user]/Nervos-Mainnet/rpc --api-key XXX
```

bsn-url和api-key都不能有引号
